### ISSUE TITLE
Investigate whether SQS still has a limit of 10 messages per SendMessageBatch

### ISSUE THREAD

**Issue by julik** [WeTransfer/sqewer#20]
It seems they still have a limit on the overall message length, but I can no longer find the limit on the send of at most 10 messages here: https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_SendMessageBatch.html

**Comment by WJWH** [comment]
First line says `Delivers up to ten messages to the specified queue.`?

**Comment by julik** [comment]
Ah. Lousy me trying to `Cmd+f+<10>`.
