### ISSUE TITLE
Refactor batch sends/receives

### ISSUE THREAD

**Issue by julik** [WeTransfer/sqewer#21]
to use `take` instead of the various message buffer objects. It will be easier to replace the actual component taking to SQS in tests and reduce the amount of boilerplate needed to keep various components operational.

**Comment by WJWH** [comment]
It would be nice if there was a `submit_multiple!` in `Sqewer::Submitter`, do you can reuse the same connection many times.

**Comment by julik** [comment]
Continuing in #57
