### ISSUE TITLE
Bumping the version

### ISSUE THREAD

**Issue by julik** [WeTransfer/sqewer#3]
To test the improved error messages we need to roll a release. Give me your email that you are going to be using for publishing gems on rubygems.org - then I can add you as a maintaner.

Afterwards, bump the tiny version number and roll a release using the standard Bundler gem tasks.  When the new version is on Rubygems we can do a `bundle update sqewer` on the dependent codebases to see it take effect. Good luck!

**Comment by WJWH** [comment]
@julik you can use my personal email adress which is wjw.hillen@gmail.com

**Comment by WJWH** [comment]
nu_backend has been updated, I'll file a pull request for monolith as soon as I get it to `bundle install`. No other repositories seem to use sqewer.

**Comment by WJWH** [comment]
`monolith` pull request is live.
