### ISSUE TITLE
Submit hangs if the SQS endpoint cannot be reached

### ISSUE THREAD

**Issue by julik** [WeTransfer/sqewer#5]
We have this when using fake_sqs and the daemon is not started up. It seems that the SDK does something that puts it into a no-timeout request mode, and it would be cool if we could kill that and let it fail non-gracefully if it is unable to connect. Currently it will just cause everything calling in to do a submit do a monumental busy wait.

**Comment by WJWH** [comment]
Do you want this just when using fake_sqs is unavailable or also when using "real" SQS? We can lift the lazy initialization of the actual AWS SQS client to somewhere at startup so it fails faster... Alternatively we can just ping the SQS url at startup and complain loudly if nothing seems to be there.

**Comment by julik** [comment]
I'd say let's just remove the neverfail 😆
