### ISSUE TITLE
Wrong instruction in README?

### ISSUE THREAD

**Issue by fabioperrella** [WeTransfer/sqewer#65]
I think there is something wrong with the instructions in README.

<img width="589" alt="image" src="https://user-images.githubusercontent.com/302303/100876884-4c0cf600-34a8-11eb-9140-4de8b7b759b6.png">

I followed them and I got the following error:

```
irb(main):016:1* class MyJob
irb(main):017:2*   def run
irb(main):018:2*     puts 'run'
irb(main):019:1*   end
irb(main):020:0> end
=> :run
irb(main):021:0> Sqewer.submit!(MyJob.new)
=> []
irb(main):022:0> Sqewer::CLI.run
Traceback (most recent call last):
        4: from /Users/fabioperrella/.rbenv/versions/2.7.1/bin/irb:23:in `<main>'
        3: from /Users/fabioperrella/.rbenv/versions/2.7.1/bin/irb:23:in `load'
        2: from /Users/fabioperrella/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/irb-1.2.7/exe/irb:11:in `<top (required)>'
        1: from (irb):22
NoMethodError (undefined method `run' for Sqewer::CLI:Module)
```

From what I saw, the method `Sqewer::CLI.run` doesn't exist and I'm almost sure it never existed.

I might be missing something 🤔 

@julik @linkyndy do you know about it?

**Comment by linkyndy** [comment]
We should correct it to `start` 👍
